[2022-04-12 04:06:03,809] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: paralled_dag.task_2 2022-04-11T00:00:00+00:00 [queued]>
[2022-04-12 04:06:04,001] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: paralled_dag.task_2 2022-04-11T00:00:00+00:00 [queued]>
[2022-04-12 04:06:04,012] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 04:06:04,013] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-04-12 04:06:04,053] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 04:06:04,232] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_2> on 2022-04-11T00:00:00+00:00
[2022-04-12 04:06:04,272] {standard_task_runner.py:52} INFO - Started process 82811 to run task
[2022-04-12 04:06:04,331] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'paralled_dag', 'task_2', '2022-04-11T00:00:00+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp6fkzabzy', '--error-file', '/tmp/tmplpvg7qtc']
[2022-04-12 04:06:04,371] {standard_task_runner.py:77} INFO - Job 7: Subtask task_2
[2022-04-12 04:06:05,212] {logging_mixin.py:104} INFO - Running <TaskInstance: paralled_dag.task_2 2022-04-11T00:00:00+00:00 [running]> on host airflowvm
[2022-04-12 04:06:05,908] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=paralled_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-11T00:00:00+00:00
[2022-04-12 04:06:05,925] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-04-12 04:06:05,926] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-04-12 04:06:06,032] {subprocess.py:75} INFO - Output:
[2022-04-12 04:06:09,109] {subprocess.py:83} INFO - Command exited with return code 0
[2022-04-12 04:06:09,379] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=paralled_dag, task_id=task_2, execution_date=20220411T000000, start_date=20220412T040603, end_date=20220412T040609
[2022-04-12 04:06:09,542] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-04-12 04:06:09,547] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 82811
[2022-04-12 04:06:09,663] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-04-12 04:06:09,663] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2022-04-12 04:06:09,737] {process_utils.py:66} INFO - Process psutil.Process(pid=82811, status='terminated', exitcode=1, started='04:06:04') (82811) terminated with exit code 1
