[2022-04-13 09:47:14,053] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: paralled_dag.task_3 2022-04-12T00:00:00+00:00 [queued]>
[2022-04-13 09:47:14,237] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: paralled_dag.task_3 2022-04-12T00:00:00+00:00 [queued]>
[2022-04-13 09:47:14,241] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-04-13 09:47:14,244] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-04-13 09:47:14,248] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-04-13 09:47:14,354] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2022-04-12T00:00:00+00:00
[2022-04-13 09:47:14,392] {standard_task_runner.py:52} INFO - Started process 12063 to run task
[2022-04-13 09:47:14,502] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'paralled_dag', 'task_3', '2022-04-12T00:00:00+00:00', '--job-id', '13', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpqxq6qi65', '--error-file', '/tmp/tmpkpwtrcsm']
[2022-04-13 09:47:14,504] {standard_task_runner.py:77} INFO - Job 13: Subtask task_3
[2022-04-13 09:47:19,782] {logging_mixin.py:104} INFO - Running <TaskInstance: paralled_dag.task_3 2022-04-12T00:00:00+00:00 [running]> on host airflowvm
[2022-04-13 09:47:20,960] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=paralled_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2022-04-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-12T00:00:00+00:00
[2022-04-13 09:47:20,962] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-04-13 09:47:20,967] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-04-13 09:47:21,023] {subprocess.py:75} INFO - Output:
[2022-04-13 09:47:24,077] {subprocess.py:83} INFO - Command exited with return code 0
[2022-04-13 09:47:24,696] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=paralled_dag, task_id=task_3, execution_date=20220412T000000, start_date=20220413T094714, end_date=20220413T094724
[2022-04-13 09:47:25,312] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-04-13 09:47:25,427] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 12063
[2022-04-13 09:47:25,442] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-04-13 09:47:25,442] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2022-04-13 09:47:25,456] {process_utils.py:66} INFO - Process psutil.Process(pid=12063, status='terminated', exitcode=1, started='09:47:13') (12063) terminated with exit code 1
